---
name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-buildx-action@v1
      # https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images#authenticating-with-the-container-registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build centos7 image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/runsfor/envs/centos:7
          target: build
          build-args: |
            CENTOS_VERSION=7
      - name: Build centos8 image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/runsfor/envs/centos:8
          target: build
          build-args: |
            CENTOS_VERSION=8
      - name: Build cartridge-cli image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/runsfor/envs/cartridge:2.4.0
          target: cartridge-cli
          build-args: |
            CENTOS_VERSION=8
            CARTRIDGE_CLI_VERSION=2.4.0
            TARANTOOL_VERSION=2.5
