---
name: Build

on:
  push:

jobs:
  build-centos:
    strategy:
      matrix:
        os: ['7', '8']
        image_type: ['base', 'build']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build centos v${{ matrix.os }} image
        uses: docker/build-push-action@v2
        with:
          push: true
          target: ${{ matrix.image_type }}
          tags: |
            ilyak/envs-centos:${{ matrix.os }}-${{ matrix.image_type }}
            ilyak/envs-centos:${{ matrix.os }}-${{ matrix.image_type }}-${{ github.sha }}
          cache-from: type=registry,ref=ilyak/envs-centos:${{ matrix.os }}-${{ matrix.image_type }}
          cache-to: type=registry,mode=max,ref=ilyak/envs-centos:${{ matrix.os }}-${{ matrix.image_type }}
          build-args: |
            CENTOS_VERSION=${{ matrix.os }}
            IMAGE_TYPE=${{ matrix.image_type }}
  build-tarantool:
    strategy:
      matrix:
        os: ['7', '8']
        image_type: ['base', 'build']
        tarantool: ['2.2', '2.3', '2.4', '2.5', '2.6']
    runs-on: ubuntu-latest
    needs: build-centos
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build tarantool v${{ matrix.tarantool }}, centos v${{ matrix.os }} ${{ matrix.image_type }} image
        uses: docker/build-push-action@v2
        with:
          push: true
          target: tarantool
          tags: |
            ilyak/envs-tarantool:${{ matrix.os }}-${{ matrix.tarantool }}-${{ matrix.image_type }}
            ilyak/envs-tarantool:${{ matrix.os }}-${{ matrix.tarantool }}-${{ matrix.image_type }}-${{ github.sha }}
          cache-from: |
            type=registry,ref=ilyak/envs-centos:${{ matrix.os }}-${{ matrix.image_type }}
            type=registry,ref=ilyak/envs-tarantool:${{ matrix.os }}-${{ matrix.tarantool }}-${{ matrix.image_type }}
          cache-to: |
            type=registry,mode=max,ref=ilyak/envs-tarantool:${{ matrix.os }}-${{ matrix.tarantool }}-${{ matrix.image_type }}
          build-args: |
            CENTOS_VERSION=${{ matrix.os }}
            IMAGE_TYPE=${{ matrix.image_type }}
            CARTRIDGE_CLI_VERSION=2.4.0
            TARANTOOL_VERSION=${{ matrix.tarantool }}
